# ================= RESTA =================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-resta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-resta
  template:
    metadata:
      labels:
        app: servicio-resta
    spec:
      containers:
      - name: contenedor-resta
        image: servicio-resta:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-resta  # <--- Java buscarÃ¡ este nombre
spec:
  type: ClusterIP
  selector:
    app: servicio-resta
  ports:
  - port: 8081
    targetPort: 8081

---
# ================= MULTI =================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-multi
  template:
    metadata:
      labels:
        app: servicio-multi
    spec:
      containers:
      - name: contenedor-multi
        image: servicio-multi:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-multi
spec:
  type: ClusterIP
  selector:
    app: servicio-multi
  ports:
  - port: 8081
    targetPort: 8081

---
# ================= DIVI =================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-divi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-divi
  template:
    metadata:
      labels:
        app: servicio-divi
    spec:
      containers:
      - name: contenedor-divi
        image: servicio-divi:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-divi
spec:
  type: ClusterIP
  selector:
    app: servicio-divi
  ports:
  - port: 8081
    targetPort: 8081
